"""
Export Module
Provides functionality to generate professional PDF reports containing candidate insights.
"""
import os
from io import BytesIO
from typing import Dict, Any

try:
    from reportlab.lib.pagesizes import letter
    from reportlab.lib import colors
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
    from reportlab.lib.units import inch
except ImportError:
    pass

def generate_pdf_report(parsed_data: Dict[str, Any], pred_data: Dict[str, Any], score_data: Dict[str, Any], gap_data: Dict[str, Any]) -> bytes:
    """Generates a professional PDF report from the analysis data."""
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=72, leftMargin=72, topMargin=72, bottomMargin=18)
    
    styles = getSampleStyleSheet()
    title_style = styles['Heading1']
    title_style.alignment = 1 # Center
    title_style.textColor = colors.HexColor("#1E3A8A")
    
    h2_style = styles['Heading2']
    h2_style.textColor = colors.HexColor("#1E3A8A")
    
    normal_style = styles['Normal']
    
    elements = []
    
    # Header
    elements.append(Paragraph("AI Career Intelligence Report", title_style))
    elements.append(Spacer(1, 0.2 * inch))
    elements.append(Paragraph("Generated by AI Career Intelligence Platform", normal_style))
    elements.append(Spacer(1, 0.5 * inch))
    
    # Candidate Details
    elements.append(Paragraph("Candidate Details", h2_style))
    elements.append(Spacer(1, 0.1 * inch))
    
    candidate_info = [
        ["Name:", parsed_data.get('name', 'N/A')],
        ["Email:", parsed_data.get('email', 'N/A')],
        ["Phone:", parsed_data.get('phone', 'N/A')]
    ]
    
    t = Table(candidate_info, colWidths=[1.5*inch, 4.5*inch])
    t.setStyle(TableStyle([
        ('FONTNAME', (0,0), (0,-1), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0,0), (-1,-1), 6),
    ]))
    elements.append(t)
    elements.append(Spacer(1, 0.3 * inch))
    
    # Career Prediction
    elements.append(Paragraph("Career Prediction", h2_style))
    elements.append(Spacer(1, 0.1 * inch))
    pred_info = [
        ["Predicted Role:", pred_data.get('predicted_role', 'N/A')],
        ["Confidence:", f"{pred_data.get('confidence', 0)}%"]
    ]
    t2 = Table(pred_info, colWidths=[1.5*inch, 4.5*inch])
    t2.setStyle(TableStyle([
        ('FONTNAME', (0,0), (0,-1), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0,0), (-1,-1), 6),
    ]))
    elements.append(t2)
    elements.append(Spacer(1, 0.3 * inch))
    
    # Resume Score
    elements.append(Paragraph("Resume Score", h2_style))
    elements.append(Spacer(1, 0.1 * inch))
    elements.append(Paragraph(f"<b>Overall Score:</b> {score_data.get('overall_score', 0)}/100 ({score_data.get('rating', 'Unknown')})", normal_style))
    elements.append(Spacer(1, 0.1 * inch))
    
    # Skill Gap & Readiness
    elements.append(Paragraph("Skill Gap & Readiness", h2_style))
    elements.append(Spacer(1, 0.1 * inch))
    elements.append(Paragraph(f"<b>Career Readiness:</b> {gap_data.get('readiness_level', 'Unknown')} ({gap_data.get('coverage_percentage', 0)}%)", normal_style))
    elements.append(Spacer(1, 0.1 * inch))
    elements.append(Paragraph(f"<b>Matching Skills:</b> {', '.join([s.title() for s in gap_data.get('matching_skills', [])])}", normal_style))
    elements.append(Spacer(1, 0.1 * inch))
    elements.append(Paragraph(f"<b>Missing Skills:</b> {', '.join([s.title() for s in gap_data.get('missing_skills', [])])}", normal_style))
    elements.append(Spacer(1, 0.3 * inch))
    
    elements.append(PageBreak())
    
    # Learning Roadmap
    elements.append(Paragraph("Personalized Learning Roadmap", h2_style))
    elements.append(Spacer(1, 0.1 * inch))
    
    for step in gap_data.get('learning_roadmap', []):
        elements.append(Paragraph(f"• {step}", normal_style))
        elements.append(Spacer(1, 0.05 * inch))
        
    elements.append(Spacer(1, 0.3 * inch))
    
    # Recommendations
    elements.append(Paragraph("Recommendations", h2_style))
    elements.append(Spacer(1, 0.1 * inch))
    
    elements.append(Paragraph("<b>Certifications:</b>", normal_style))
    for c in gap_data.get('recommended_certifications', []):
        elements.append(Paragraph(f"- {c}", normal_style))
    elements.append(Spacer(1, 0.1 * inch))
        
    elements.append(Paragraph("<b>Portfolio Projects:</b>", normal_style))
    for p in gap_data.get('recommended_projects', []):
        elements.append(Paragraph(f"- {p}", normal_style))
    elements.append(Spacer(1, 0.1 * inch))
        
    elements.append(Paragraph("<b>Interview Topics:</b>", normal_style))
    for i in gap_data.get('interview_topics', []):
        elements.append(Paragraph(f"- {i}", normal_style))
        
    # Build PDF
    doc.build(elements)
    
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes
